name: surf-freebuild-whitelist
version: '${version}'
main: dev.slne.surf.freebuild.whitelist.PaperMain
api-version: '1.21'
folia-supported: true
authors:
  - red
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
